// Generated by gencpp from file nubot_common/BallHandleResponse.msg
// DO NOT EDIT!


#ifndef NUBOT_COMMON_MESSAGE_BALLHANDLERESPONSE_H
#define NUBOT_COMMON_MESSAGE_BALLHANDLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nubot_common
{
template <class ContainerAllocator>
struct BallHandleResponse_
{
  typedef BallHandleResponse_<ContainerAllocator> Type;

  BallHandleResponse_()
    : BallIsHolding(0)  {
    }
  BallHandleResponse_(const ContainerAllocator& _alloc)
    : BallIsHolding(0)  {
  (void)_alloc;
    }



   typedef int64_t _BallIsHolding_type;
  _BallIsHolding_type BallIsHolding;




  typedef boost::shared_ptr< ::nubot_common::BallHandleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nubot_common::BallHandleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BallHandleResponse_

typedef ::nubot_common::BallHandleResponse_<std::allocator<void> > BallHandleResponse;

typedef boost::shared_ptr< ::nubot_common::BallHandleResponse > BallHandleResponsePtr;
typedef boost::shared_ptr< ::nubot_common::BallHandleResponse const> BallHandleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nubot_common::BallHandleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nubot_common::BallHandleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nubot_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nubot_common': ['/home/nubot8/dynamic_allocation/gazebo_visual/src/nubot_common/msgs'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nubot_common::BallHandleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nubot_common::BallHandleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nubot_common::BallHandleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nubot_common::BallHandleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nubot_common::BallHandleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nubot_common::BallHandleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nubot_common::BallHandleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "371e9ec4fdab9c30277b932f121cf460";
  }

  static const char* value(const ::nubot_common::BallHandleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x371e9ec4fdab9c30ULL;
  static const uint64_t static_value2 = 0x277b932f121cf460ULL;
};

template<class ContainerAllocator>
struct DataType< ::nubot_common::BallHandleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nubot_common/BallHandleResponse";
  }

  static const char* value(const ::nubot_common::BallHandleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nubot_common::BallHandleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 BallIsHolding\n\
\n\
";
  }

  static const char* value(const ::nubot_common::BallHandleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nubot_common::BallHandleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.BallIsHolding);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BallHandleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nubot_common::BallHandleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nubot_common::BallHandleResponse_<ContainerAllocator>& v)
  {
    s << indent << "BallIsHolding: ";
    Printer<int64_t>::stream(s, indent + "  ", v.BallIsHolding);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NUBOT_COMMON_MESSAGE_BALLHANDLERESPONSE_H
