// Generated by gencpp from file nubot_common/BallHandle.msg
// DO NOT EDIT!


#ifndef NUBOT_COMMON_MESSAGE_BALLHANDLE_H
#define NUBOT_COMMON_MESSAGE_BALLHANDLE_H

#include <ros/service_traits.h>


#include <nubot_common/BallHandleRequest.h>
#include <nubot_common/BallHandleResponse.h>


namespace nubot_common
{

struct BallHandle
{

typedef BallHandleRequest Request;
typedef BallHandleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BallHandle
} // namespace nubot_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nubot_common::BallHandle > {
  static const char* value()
  {
    return "f352f0080766880a151542e750a50ea8";
  }

  static const char* value(const ::nubot_common::BallHandle&) { return value(); }
};

template<>
struct DataType< ::nubot_common::BallHandle > {
  static const char* value()
  {
    return "nubot_common/BallHandle";
  }

  static const char* value(const ::nubot_common::BallHandle&) { return value(); }
};


// service_traits::MD5Sum< ::nubot_common::BallHandleRequest> should match 
// service_traits::MD5Sum< ::nubot_common::BallHandle > 
template<>
struct MD5Sum< ::nubot_common::BallHandleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nubot_common::BallHandle >::value();
  }
  static const char* value(const ::nubot_common::BallHandleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nubot_common::BallHandleRequest> should match 
// service_traits::DataType< ::nubot_common::BallHandle > 
template<>
struct DataType< ::nubot_common::BallHandleRequest>
{
  static const char* value()
  {
    return DataType< ::nubot_common::BallHandle >::value();
  }
  static const char* value(const ::nubot_common::BallHandleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nubot_common::BallHandleResponse> should match 
// service_traits::MD5Sum< ::nubot_common::BallHandle > 
template<>
struct MD5Sum< ::nubot_common::BallHandleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nubot_common::BallHandle >::value();
  }
  static const char* value(const ::nubot_common::BallHandleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nubot_common::BallHandleResponse> should match 
// service_traits::DataType< ::nubot_common::BallHandle > 
template<>
struct DataType< ::nubot_common::BallHandleResponse>
{
  static const char* value()
  {
    return DataType< ::nubot_common::BallHandle >::value();
  }
  static const char* value(const ::nubot_common::BallHandleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NUBOT_COMMON_MESSAGE_BALLHANDLE_H
