// Generated by gencpp from file nubot_common/currentCmd.msg
// DO NOT EDIT!


#ifndef NUBOT_COMMON_MESSAGE_CURRENTCMD_H
#define NUBOT_COMMON_MESSAGE_CURRENTCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nubot_common
{
template <class ContainerAllocator>
struct currentCmd_
{
  typedef currentCmd_<ContainerAllocator> Type;

  currentCmd_()
    : current(0)  {
    }
  currentCmd_(const ContainerAllocator& _alloc)
    : current(0)  {
  (void)_alloc;
    }



   typedef int32_t _current_type;
  _current_type current;




  typedef boost::shared_ptr< ::nubot_common::currentCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nubot_common::currentCmd_<ContainerAllocator> const> ConstPtr;

}; // struct currentCmd_

typedef ::nubot_common::currentCmd_<std::allocator<void> > currentCmd;

typedef boost::shared_ptr< ::nubot_common::currentCmd > currentCmdPtr;
typedef boost::shared_ptr< ::nubot_common::currentCmd const> currentCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nubot_common::currentCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nubot_common::currentCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nubot_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nubot_common': ['/home/nubot8/dynamic_allocation/gazebo_visual/src/nubot_common/msgs'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nubot_common::currentCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nubot_common::currentCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nubot_common::currentCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nubot_common::currentCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nubot_common::currentCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nubot_common::currentCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nubot_common::currentCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034ddbc97d77dfabd91aa8abddfb4453";
  }

  static const char* value(const ::nubot_common::currentCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034ddbc97d77dfabULL;
  static const uint64_t static_value2 = 0xd91aa8abddfb4453ULL;
};

template<class ContainerAllocator>
struct DataType< ::nubot_common::currentCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nubot_common/currentCmd";
  }

  static const char* value(const ::nubot_common::currentCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nubot_common::currentCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 current\n\
\n\
";
  }

  static const char* value(const ::nubot_common::currentCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nubot_common::currentCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct currentCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nubot_common::currentCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nubot_common::currentCmd_<ContainerAllocator>& v)
  {
    s << indent << "current: ";
    Printer<int32_t>::stream(s, indent + "  ", v.current);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NUBOT_COMMON_MESSAGE_CURRENTCMD_H
