// Generated by gencpp from file nubot_common/Shoot.msg
// DO NOT EDIT!


#ifndef NUBOT_COMMON_MESSAGE_SHOOT_H
#define NUBOT_COMMON_MESSAGE_SHOOT_H

#include <ros/service_traits.h>


#include <nubot_common/ShootRequest.h>
#include <nubot_common/ShootResponse.h>


namespace nubot_common
{

struct Shoot
{

typedef ShootRequest Request;
typedef ShootResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Shoot
} // namespace nubot_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nubot_common::Shoot > {
  static const char* value()
  {
    return "5f7b2fca861afe65dc92d3f6a153bbec";
  }

  static const char* value(const ::nubot_common::Shoot&) { return value(); }
};

template<>
struct DataType< ::nubot_common::Shoot > {
  static const char* value()
  {
    return "nubot_common/Shoot";
  }

  static const char* value(const ::nubot_common::Shoot&) { return value(); }
};


// service_traits::MD5Sum< ::nubot_common::ShootRequest> should match 
// service_traits::MD5Sum< ::nubot_common::Shoot > 
template<>
struct MD5Sum< ::nubot_common::ShootRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nubot_common::Shoot >::value();
  }
  static const char* value(const ::nubot_common::ShootRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nubot_common::ShootRequest> should match 
// service_traits::DataType< ::nubot_common::Shoot > 
template<>
struct DataType< ::nubot_common::ShootRequest>
{
  static const char* value()
  {
    return DataType< ::nubot_common::Shoot >::value();
  }
  static const char* value(const ::nubot_common::ShootRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nubot_common::ShootResponse> should match 
// service_traits::MD5Sum< ::nubot_common::Shoot > 
template<>
struct MD5Sum< ::nubot_common::ShootResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nubot_common::Shoot >::value();
  }
  static const char* value(const ::nubot_common::ShootResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nubot_common::ShootResponse> should match 
// service_traits::DataType< ::nubot_common::Shoot > 
template<>
struct DataType< ::nubot_common::ShootResponse>
{
  static const char* value()
  {
    return DataType< ::nubot_common::Shoot >::value();
  }
  static const char* value(const ::nubot_common::ShootResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NUBOT_COMMON_MESSAGE_SHOOT_H
