# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from nubot_common/BallInfo3d.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import nubot_common.msg
import std_msgs.msg

class BallInfo3d(genpy.Message):
  _md5sum = "6634a529c2fba000f06cf99f5ab31312"
  _type = "nubot_common/BallInfo3d"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
Point3d   pos
Point3d   velocity
bool      pos_known_3d
bool      pos_known_2d
bool      velocity_known

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: nubot_common/Point3d
float32 x
float32 y
float32 z
"""
  __slots__ = ['header','pos','velocity','pos_known_3d','pos_known_2d','velocity_known']
  _slot_types = ['std_msgs/Header','nubot_common/Point3d','nubot_common/Point3d','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,pos,velocity,pos_known_3d,pos_known_2d,velocity_known

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BallInfo3d, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pos is None:
        self.pos = nubot_common.msg.Point3d()
      if self.velocity is None:
        self.velocity = nubot_common.msg.Point3d()
      if self.pos_known_3d is None:
        self.pos_known_3d = False
      if self.pos_known_2d is None:
        self.pos_known_2d = False
      if self.velocity_known is None:
        self.velocity_known = False
    else:
      self.header = std_msgs.msg.Header()
      self.pos = nubot_common.msg.Point3d()
      self.velocity = nubot_common.msg.Point3d()
      self.pos_known_3d = False
      self.pos_known_2d = False
      self.velocity_known = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6f3B().pack(_x.pos.x, _x.pos.y, _x.pos.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.pos_known_3d, _x.pos_known_2d, _x.velocity_known))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pos is None:
        self.pos = nubot_common.msg.Point3d()
      if self.velocity is None:
        self.velocity = nubot_common.msg.Point3d()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 27
      (_x.pos.x, _x.pos.y, _x.pos.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.pos_known_3d, _x.pos_known_2d, _x.velocity_known,) = _get_struct_6f3B().unpack(str[start:end])
      self.pos_known_3d = bool(self.pos_known_3d)
      self.pos_known_2d = bool(self.pos_known_2d)
      self.velocity_known = bool(self.velocity_known)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6f3B().pack(_x.pos.x, _x.pos.y, _x.pos.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.pos_known_3d, _x.pos_known_2d, _x.velocity_known))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pos is None:
        self.pos = nubot_common.msg.Point3d()
      if self.velocity is None:
        self.velocity = nubot_common.msg.Point3d()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 27
      (_x.pos.x, _x.pos.y, _x.pos.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.pos_known_3d, _x.pos_known_2d, _x.velocity_known,) = _get_struct_6f3B().unpack(str[start:end])
      self.pos_known_3d = bool(self.pos_known_3d)
      self.pos_known_2d = bool(self.pos_known_2d)
      self.velocity_known = bool(self.velocity_known)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_6f3B = None
def _get_struct_6f3B():
    global _struct_6f3B
    if _struct_6f3B is None:
        _struct_6f3B = struct.Struct("<6f3B")
    return _struct_6f3B
