# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from nubot_common/RobotInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import nubot_common.msg
import std_msgs.msg

class RobotInfo(genpy.Message):
  _md5sum = "a028ed4c7ddb1dc95486b7c6059da8ad"
  _type = "nubot_common/RobotInfo"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
int32    AgentID
Point2d  pos
Angle    heading
float32  vrot
Point2d  vtrans
bool     iskick     
bool     isvalid 
bool     isstuck 
bool     isdribble
char     current_role
float32  role_time
Point2d  target
 

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: nubot_common/Point2d
float32 x
float32 y

================================================================================
MSG: nubot_common/Angle
float32 theta
"""
  __slots__ = ['header','AgentID','pos','heading','vrot','vtrans','iskick','isvalid','isstuck','isdribble','current_role','role_time','target']
  _slot_types = ['std_msgs/Header','int32','nubot_common/Point2d','nubot_common/Angle','float32','nubot_common/Point2d','bool','bool','bool','bool','char','float32','nubot_common/Point2d']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,AgentID,pos,heading,vrot,vtrans,iskick,isvalid,isstuck,isdribble,current_role,role_time,target

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.AgentID is None:
        self.AgentID = 0
      if self.pos is None:
        self.pos = nubot_common.msg.Point2d()
      if self.heading is None:
        self.heading = nubot_common.msg.Angle()
      if self.vrot is None:
        self.vrot = 0.
      if self.vtrans is None:
        self.vtrans = nubot_common.msg.Point2d()
      if self.iskick is None:
        self.iskick = False
      if self.isvalid is None:
        self.isvalid = False
      if self.isstuck is None:
        self.isstuck = False
      if self.isdribble is None:
        self.isdribble = False
      if self.current_role is None:
        self.current_role = 0
      if self.role_time is None:
        self.role_time = 0.
      if self.target is None:
        self.target = nubot_common.msg.Point2d()
    else:
      self.header = std_msgs.msg.Header()
      self.AgentID = 0
      self.pos = nubot_common.msg.Point2d()
      self.heading = nubot_common.msg.Angle()
      self.vrot = 0.
      self.vtrans = nubot_common.msg.Point2d()
      self.iskick = False
      self.isvalid = False
      self.isstuck = False
      self.isdribble = False
      self.current_role = 0
      self.role_time = 0.
      self.target = nubot_common.msg.Point2d()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_i6f5B3f().pack(_x.AgentID, _x.pos.x, _x.pos.y, _x.heading.theta, _x.vrot, _x.vtrans.x, _x.vtrans.y, _x.iskick, _x.isvalid, _x.isstuck, _x.isdribble, _x.current_role, _x.role_time, _x.target.x, _x.target.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pos is None:
        self.pos = nubot_common.msg.Point2d()
      if self.heading is None:
        self.heading = nubot_common.msg.Angle()
      if self.vtrans is None:
        self.vtrans = nubot_common.msg.Point2d()
      if self.target is None:
        self.target = nubot_common.msg.Point2d()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 45
      (_x.AgentID, _x.pos.x, _x.pos.y, _x.heading.theta, _x.vrot, _x.vtrans.x, _x.vtrans.y, _x.iskick, _x.isvalid, _x.isstuck, _x.isdribble, _x.current_role, _x.role_time, _x.target.x, _x.target.y,) = _get_struct_i6f5B3f().unpack(str[start:end])
      self.iskick = bool(self.iskick)
      self.isvalid = bool(self.isvalid)
      self.isstuck = bool(self.isstuck)
      self.isdribble = bool(self.isdribble)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_i6f5B3f().pack(_x.AgentID, _x.pos.x, _x.pos.y, _x.heading.theta, _x.vrot, _x.vtrans.x, _x.vtrans.y, _x.iskick, _x.isvalid, _x.isstuck, _x.isdribble, _x.current_role, _x.role_time, _x.target.x, _x.target.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pos is None:
        self.pos = nubot_common.msg.Point2d()
      if self.heading is None:
        self.heading = nubot_common.msg.Angle()
      if self.vtrans is None:
        self.vtrans = nubot_common.msg.Point2d()
      if self.target is None:
        self.target = nubot_common.msg.Point2d()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 45
      (_x.AgentID, _x.pos.x, _x.pos.y, _x.heading.theta, _x.vrot, _x.vtrans.x, _x.vtrans.y, _x.iskick, _x.isvalid, _x.isstuck, _x.isdribble, _x.current_role, _x.role_time, _x.target.x, _x.target.y,) = _get_struct_i6f5B3f().unpack(str[start:end])
      self.iskick = bool(self.iskick)
      self.isvalid = bool(self.isvalid)
      self.isstuck = bool(self.isstuck)
      self.isdribble = bool(self.isdribble)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i6f5B3f = None
def _get_struct_i6f5B3f():
    global _struct_i6f5B3f
    if _struct_i6f5B3f is None:
        _struct_i6f5B3f = struct.Struct("<i6f5B3f")
    return _struct_i6f5B3f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
