(cl:in-package nubot_common-msg)
(cl:export '(HEADER-VAL
          HEADER
          AGENTID-VAL
          AGENTID
          TARGETNUM1-VAL
          TARGETNUM1
          TARGETNUM2-VAL
          TARGETNUM2
          TARGETNUM3-VAL
          TARGETNUM3
          TARGETNUM4-VAL
          TARGETNUM4
          STATICPASSNUM-VAL
          STATICPASSNUM
          STATICCATCHNUM-VAL
          STATICCATCHNUM
          ROLE-VAL
          ROLE
          ACTION-VAL
          ACTION
          IS_DRIBBLE-VAL
          IS_DRIBBLE
          IS_KICKOFF-VAL
          IS_KICKOFF
          ROLE_TIME-VAL
          ROLE_TIME
          PASS_CMD-VAL
          PASS_CMD
))